### ISSUE TITLE
Mac M1 Installation Issues

### ISSUE THREAD

**Issue by caseywescott** [AlexW00/clockwork#1]
Hi, 

Has anyone been able to run the plugin on a Mac M1 ?  I'm placing the file in the correct plugin folder but keep getting an error in both FL and Logic. Has anyone been able to install and avoid being blocked to being an unidentified developer? Any attempt is unresponsive. 

Thanks

**Comment by caseywescott** [comment]
Sorry - I found answers to my question.

**Comment by AlexW00** [comment]
> Sorry - I found answers to my question.

Great to hear you got it running. For anyone else, who has the same problem, here is the solution:
https://www.youtube.com/watch?v=S-FH9Tlkj5M

Btw, I got a newer version of the plugin with more arpeggio features on my hard drive. If anyone's interested, I can release it.



https://user-images.githubusercontent.com/55558407/208391026-dab1f1e9-ee34-4854-aed7-3668daf3aeea.mp4
